name: Tests MediTrack API

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: meditrackadmin
          POSTGRES_PASSWORD: MotDePasseComplexe123!
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./api-backend
        run: npm install

      - name: Clear Jest cache
        working-directory: ./api-backend
        run: npx jest --clearCache

      - name: Run tests
        working-directory: ./api-backend
        env:
          DB_HOST: localhost
          DB_USER: meditrackadmin
          DB_PASSWORD: MotDePasseComplexe123!
          DB_NAME: postgres
          DB_PORT: 5432
        run: npm test
